name: 🚀 Feature Request
description: Suggest a new feature for the Cyntek procurement portal
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Which user personas will benefit from this feature?
      multiple: true
      options:
        - Org Admin
        - Buyer 
        - Requester
        - Cyntek Admin
        - All Users
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a [user type], I need [functionality] so that [benefit]..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: "The feature should work by..."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What specific requirements must be met?
      placeholder: |
        - [ ] User can...
        - [ ] System validates...  
        - [ ] Admin receives notification...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Business Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Important for user experience  
        - High - Critical for business operations
        - Urgent - Blocking current operations
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Considerations
      description: Any technical constraints, dependencies, or implementation notes?
      placeholder: "This feature may require changes to..."

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which part of the application is affected?
      multiple: true
      options:
        - Authentication & Permissions
        - Parts Catalog & Search
        - Shopping Cart & Orders
        - Purchase Request System  
        - Admin Interface
        - Analytics & Reporting
        - Email Notifications
        - Database & API
        - UI/UX Design
        - Mobile Responsiveness